package fr.d4.ihm;

import fr.d4.dto.AgenceDto;
import fr.d4.dto.ClientDto;


	public class CreationAgence extends javax.swing.JFrame {

	    /**
		 * 
		 */
		private static final long serialVersionUID = 1L;
		/**
	     * Creates new form RegisterForm
	     */
	    public CreationAgence() {
	        initComponents();
	    }

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	    private void initComponents() {

	        jPanel1 = new javax.swing.JPanel();
	        jLabelMn = new javax.swing.JLabel();
	        jLabelClose = new javax.swing.JLabel();
	        jTextField2 = new javax.swing.JTextField();
	        jLabel1 = new javax.swing.JLabel();
	        jPanel2 = new javax.swing.JPanel();
	        jLabel4 = new javax.swing.JLabel();
	        jTextField1 = new javax.swing.JTextField();
	        jButton2 = new javax.swing.JButton();
	        jLabel2 = new javax.swing.JLabel();
	        jButtonRegister = new javax.swing.JButton();
	        jLabel6 = new javax.swing.JLabel();
	        jScrollPane1 = new javax.swing.JScrollPane();
	        jTextArea1 = new javax.swing.JTextArea();

	        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
	        setUndecorated(true);

	        jPanel1.setBackground(new java.awt.Color(242, 120, 75));

//	        jLabelMn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
//	        jLabelMn.setForeground(new java.awt.Color(255, 255, 255));
//	        jLabelMn.setText("-");
//	        jLabelMn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
//	        jLabelMn.addMouseListener(new java.awt.event.MouseAdapter() {
//	            public void mouseClicked(java.awt.event.MouseEvent evt) {
//	                jLabelMnMouseClicked(evt);
//	            }
//	        });
//
//	        jLabelClose.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
//	        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
//	        jLabelClose.setText("X");
//	        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
//	        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
//	            public void mouseClicked(java.awt.event.MouseEvent evt) {
//	                jLabelCloseMouseClicked(evt);
//	            }
//	        });

	        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
	        jLabel1.setText("LCR");

	        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
	        jPanel1.setLayout(jPanel1Layout);
	        jPanel1Layout.setHorizontalGroup(
	            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel1Layout.createSequentialGroup()
	                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
	                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addGap(170, 170, 170)
	                        .addComponent(jLabelMn)
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                        .addComponent(jLabelClose)
	                        .addGap(18, 18, 18))
	                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
	                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addGap(68, 68, 68))))
	        );
	        jPanel1Layout.setVerticalGroup(
	            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel1Layout.createSequentialGroup()
	                .addContainerGap()
	                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                        .addComponent(jLabelClose)
	                        .addComponent(jLabelMn))
	                    .addComponent(jLabel1))
	                .addGap(18, 18, 18)
	                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addContainerGap(27, Short.MAX_VALUE))
	        );

	        jPanel2.setBackground(new java.awt.Color(51, 110, 123));

	        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
	        jLabel4.setForeground(new java.awt.Color(236, 240, 241));
	        jLabel4.setText("Adresse :");

	        jTextField1.setBackground(new java.awt.Color(22, 160, 133));
	        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
	        jTextField1.setForeground(new java.awt.Color(228, 241, 254));

	        jButton2.setBackground(new java.awt.Color(241, 71, 71));
	        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
	        jButton2.setForeground(new java.awt.Color(255, 255, 255));
	        jButton2.setText("Cancel");
	        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
	            public void mouseClicked(java.awt.event.MouseEvent evt) {
	                jButtonRegisterMouseClicked(evt);
	            }
	        });
	        jButton2.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButton2ActionPerformed(evt);
	            }
	        });

	        
	        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
	        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
	        jLabel2.setText("Création Agence");

	        jButtonRegister.setBackground(new java.awt.Color(34, 167, 240));
	        jButtonRegister.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
	        jButtonRegister.setForeground(new java.awt.Color(255, 255, 255));
	        jButtonRegister.setText("Valider");
	        jButtonRegister.addMouseListener(new java.awt.event.MouseAdapter() {
	            public void mouseClicked(java.awt.event.MouseEvent evt) {
	                jButtonRegisterMouseClicked(evt);
	            }
	        });
	        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButtonRegisterActionPerformed(evt);
	            }
	        });

	        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
	        jLabel6.setForeground(new java.awt.Color(236, 240, 241));
	        jLabel6.setText("Nom :");

	        jTextArea1.setBackground(new java.awt.Color(22, 160, 133));
	        jTextArea1.setColumns(20);
	        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
	        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
	        jTextArea1.setRows(5);
	        jScrollPane1.setViewportView(jTextArea1);

	        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
	        jPanel2.setLayout(jPanel2Layout);
	        jPanel2Layout.setHorizontalGroup(
	            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
	                .addGap(54, 54, 54)
	                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(jPanel2Layout.createSequentialGroup()
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
	                        .addComponent(jButton2)
	                        .addGap(47, 47, 47)
	                        .addComponent(jButtonRegister)
	                        .addGap(122, 122, 122))
	                    .addGroup(jPanel2Layout.createSequentialGroup()
	                        .addGap(53, 53, 53)
	                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
	                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
	            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
	                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                .addComponent(jLabel2)
	                .addGap(143, 143, 143))
	        );
	        jPanel2Layout.setVerticalGroup(
	            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel2Layout.createSequentialGroup()
	                .addGap(47, 47, 47)
	                .addComponent(jLabel2)
	                .addGap(52, 52, 52)
	                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel6)
	                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addGap(26, 26, 26)
	                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addComponent(jLabel4)
	                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addGap(18, 18, 18)
	                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jButtonRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addContainerGap(89, Short.MAX_VALUE))
	        );

	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	        getContentPane().setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addGap(0, 0, Short.MAX_VALUE))
	            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	        );

	        pack();
	        setLocationRelativeTo(null);
	    }// </editor-fold>                                                        

	    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {                                                
	    	AgenceDto ad = new AgenceDto();
	    	ad.insertAgence(jTextField1.getText(),jTextArea1.getText());
	    	ClientDto cd = new ClientDto();
	    	Object[][] data = cd.requeteClient();
			Menu m = new Menu(data);
			m.setVisible(true);
			setVisible(false);
	    }                                               

	    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                                
	    	ClientDto cd = new ClientDto();
	    	Object[][] data = cd.requeteClient();
			Menu m = new Menu(data);
			m.setVisible(true);
			setVisible(false);
	    }  
	    
	    private void jButtonRegisterMouseClicked(java.awt.event.MouseEvent evt) {                                             
	        // TODO add your handling code here:
	    }                                            

	    /**
	     * @param args the command line arguments
	     */
	    public static void main(String args[]) {
	        /* Set the Nimbus look and feel */
	        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	         */
	        try {
	            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
	                if ("Nimbus".equals(info.getName())) {
	                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
	                    break;
	                }
	            }
	        } catch (ClassNotFoundException ex) {
	            java.util.logging.Logger.getLogger(CreationAgence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (InstantiationException ex) {
	            java.util.logging.Logger.getLogger(CreationAgence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (IllegalAccessException ex) {
	            java.util.logging.Logger.getLogger(CreationAgence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	            java.util.logging.Logger.getLogger(CreationAgence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        }
	        //</editor-fold>

	        /* Create and display the form */
	        java.awt.EventQueue.invokeLater(new Runnable() {
	            public void run() {
	                new CreationAgence().setVisible(true);
	            }
	        });
	    }

	    // Variables declaration - do not modify                     
	    private javax.swing.JButton jButton2;
	    private javax.swing.JButton jButtonRegister;
	    private javax.swing.JLabel jLabel1;
	    private javax.swing.JLabel jLabel2;
	    private javax.swing.JLabel jLabel4;
	    private javax.swing.JLabel jLabel6;
	    private javax.swing.JLabel jLabelClose;
	    private javax.swing.JLabel jLabelMn;
	    private javax.swing.JPanel jPanel1;
	    private javax.swing.JPanel jPanel2;
	    private javax.swing.JScrollPane jScrollPane1;
	    private javax.swing.JTextArea jTextArea1;
	    private javax.swing.JTextField jTextField1;
	    private javax.swing.JTextField jTextField2;
	    // End of variables declaration                   
	}

