package fr.d4.ihm;


public class OperationRetrait extends javax.swing.JFrame {

	
	

	    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
		/**
	     * Creates new form OperationRetrait
	     */
	    public OperationRetrait() {
	        initComponents();
	    }

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	    private void initComponents() {

	        jPanel3 = new javax.swing.JPanel();
	        jPanel1 = new javax.swing.JPanel();
	        jLabelMn = new javax.swing.JLabel();
	        jLabelClose = new javax.swing.JLabel();
	        jLabel1 = new javax.swing.JLabel();
	        jPanel2 = new javax.swing.JPanel();
	        jButton2 = new javax.swing.JButton();
	        jLabel2 = new javax.swing.JLabel();
	        jButtonRegister = new javax.swing.JButton();
	        jLabel6 = new javax.swing.JLabel();
	        jTextField1 = new javax.swing.JTextField();

	        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
	        jPanel3.setLayout(jPanel3Layout);
	        jPanel3Layout.setHorizontalGroup(
	            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGap(0, 100, Short.MAX_VALUE)
	        );
	        jPanel3Layout.setVerticalGroup(
	            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGap(0, 100, Short.MAX_VALUE)
	        );

	        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
	        setUndecorated(true);

	        jPanel1.setBackground(new java.awt.Color(242, 120, 75));

//	        jLabelMn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
//	        jLabelMn.setForeground(new java.awt.Color(255, 255, 255));
//	        jLabelMn.setText("-");
//	        jLabelMn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
//	        jLabelMn.addMouseListener(new java.awt.event.MouseAdapter() {
//	            public void mouseClicked(java.awt.event.MouseEvent evt) {
//	                jLabelMnMouseClicked(evt);
//	            }
//	        });
//
//	        jLabelClose.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
//	        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
//	        jLabelClose.setText("X");
//	        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
//	        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
//	            public void mouseClicked(java.awt.event.MouseEvent evt) {
//	                jLabelCloseMouseClicked(evt);
//	            }
//	        });

	        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
	        jLabel1.setText("LCR");

	        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
	        jPanel1.setLayout(jPanel1Layout);
	        jPanel1Layout.setHorizontalGroup(
	            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel1Layout.createSequentialGroup()
	                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addGap(147, 147, 147)
	                .addComponent(jLabelMn)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                .addComponent(jLabelClose)
	                .addGap(18, 18, 18))
	        );
	        jPanel1Layout.setVerticalGroup(
	            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel1Layout.createSequentialGroup()
	                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(jPanel1Layout.createSequentialGroup()
	                        .addContainerGap()
	                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                            .addComponent(jLabelClose)
	                            .addComponent(jLabelMn)))
	                    .addGroup(jPanel1Layout.createSequentialGroup()
	                        .addGap(30, 30, 30)
	                        .addComponent(jLabel1)))
	                .addContainerGap(36, Short.MAX_VALUE))
	        );

	        jPanel2.setBackground(new java.awt.Color(51, 110, 123));

	        jButton2.setBackground(new java.awt.Color(241, 71, 71));
	        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
	        jButton2.setForeground(new java.awt.Color(255, 255, 255));
	        jButton2.setText("Cancel");

	        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
	        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
	        jLabel2.setText("Operation Retrait");

	        jButtonRegister.setBackground(new java.awt.Color(34, 167, 240));
	        jButtonRegister.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
	        jButtonRegister.setForeground(new java.awt.Color(255, 255, 255));
	        jButtonRegister.setText("Valider");
	        jButtonRegister.addMouseListener(new java.awt.event.MouseAdapter() {
	            public void mouseClicked(java.awt.event.MouseEvent evt) {
	                jButtonRegisterMouseClicked(evt);
	            }
	        });
	        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButtonRegisterActionPerformed(evt);
	            }
	        });

	        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
	        jLabel6.setForeground(new java.awt.Color(236, 240, 241));
	        jLabel6.setText("Montant :");

	        jTextField1.setBackground(new java.awt.Color(22, 160, 133));
	        jTextField1.setForeground(new java.awt.Color(255, 255, 255));

	        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
	        jPanel2.setLayout(jPanel2Layout);
	        jPanel2Layout.setHorizontalGroup(
	            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel2Layout.createSequentialGroup()
	                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
	                    .addGroup(jPanel2Layout.createSequentialGroup()
	                        .addComponent(jButton2)
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                        .addComponent(jButtonRegister))
	                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addGap(89, 89, 89))
	            .addGroup(jPanel2Layout.createSequentialGroup()
	                .addGap(118, 118, 118)
	                .addComponent(jLabel2)
	                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	        );
	        jPanel2Layout.setVerticalGroup(
	            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel2Layout.createSequentialGroup()
	                .addGap(49, 49, 49)
	                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	                    .addGroup(jPanel2Layout.createSequentialGroup()
	                        .addComponent(jLabel2)
	                        .addGap(73, 73, 73)
	                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
	                    .addComponent(jLabel6))
	                .addGap(53, 53, 53)
	                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jButtonRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addContainerGap(103, Short.MAX_VALUE))
	        );

	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	        getContentPane().setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	        );

	        pack();
	    }// </editor-fold>                        

	    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {                                                

	    }                                               

	    private void jButtonRegisterMouseClicked(java.awt.event.MouseEvent evt) {                                             
	        // TODO add your handling code here:
	    }                                            

	    /**
	     * @param args the command line arguments
	     */
	    public static void main(String args[]) {
	        /* Set the Nimbus look and feel */
	        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	         */
	        try {
	            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
	                if ("Nimbus".equals(info.getName())) {
	                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
	                    break;
	                }
	            }
	        } catch (ClassNotFoundException ex) {
	            java.util.logging.Logger.getLogger(OperationRetrait.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (InstantiationException ex) {
	            java.util.logging.Logger.getLogger(OperationRetrait.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (IllegalAccessException ex) {
	            java.util.logging.Logger.getLogger(OperationRetrait.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	            java.util.logging.Logger.getLogger(OperationRetrait.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        }
	        //</editor-fold>

	        /* Create and display the form */
	        java.awt.EventQueue.invokeLater(new Runnable() {
	            public void run() {
	                new OperationRetrait().setVisible(true);
	            }
	        });
	    }

	    // Variables declaration - do not modify                     
	    private javax.swing.JButton jButton2;
	    private javax.swing.JButton jButtonRegister;
	    private javax.swing.JLabel jLabel1;
	    private javax.swing.JLabel jLabel2;
	    private javax.swing.JLabel jLabel6;
	    private javax.swing.JLabel jLabelClose;
	    private javax.swing.JLabel jLabelMn;
	    private javax.swing.JPanel jPanel1;
	    private javax.swing.JPanel jPanel2;
	    private javax.swing.JPanel jPanel3;
	    private javax.swing.JTextField jTextField1;
	    // End of variables declaration                   
	}

